### ISSUE TITLE
Appium 2.0

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7175]
Appium, rather than bundling all the separate drivers by default, becomes a driver management interface (in addition to continuing to play the role of automation frontend server). Appium gets a set of CLI tools for users to pick and choose which drivers and versions of drivers they want to use via Appium.

[Spec for Appium 2.0](https://gist.github.com/jlipps/651b62316603400cabc95ff0f9faf70f)

Additional breaking changes, upgrades, or dev tasks to perform while we are allowed to make breaking changes:

* [ ] Remove ability to use most server args (in favor of --default-capabilities)
* [ ] Remove support for appium-ios-driver (move it to boneyard and pull out shared code either into appium-xcuitest-driver or if we want, into appium-ios-base)
* [ ] Remove support for appium-android-driver (move it to boneyard and pull out shared code either into appium-uiautomator2-driver, or since espresso might also depend on it, into appium-android-base)
* [ ] Remove support for appium-selendroid-driver (move it to boneyard)
* [ ] Update all build scripts to use minimal transpilation (at this point, targeting Node 10 as a minimum, we should able to get away with very little transpilation, maybe just the `import` stuff?) I am not sure how easy this is to do with Babel, hopefully it is smart enough to take a target version of Node and not transpile more than necessary.
* [ ] See if we can move away from the Winston logger to something more flexible and universal that could be shared by BaseDriver. Since we're making breaking changes we'd be OK with a log format update.
* [ ] run WDA bootstrap script on xcuitest driver install, not first session run?

(Each of the above should probably be turned into their own issue and linked here)

**Comment by jlipps** [comment]
Been thinking more about Appium 2.0, and made a concrete proposal for how it'd work! https://gist.github.com/jlipps/651b62316603400cabc95ff0f9faf70f

cc @imurchie @dpgraham @mykola-mokhnach @sravanmedarapu @bootstraponline @moizjv

**Comment by pavanbachu0604** [comment]
Is there a way we can include capabilities to capture the Memory CPU logs in iOS Devices?

**Comment by KazuCocoa** [comment]
👣

**Comment by mykola-mokhnach** [comment]
Different drivers share common several modules. For example, android driver depends on base driver and appium-adb as well as selendroid driver and uiautomator2 drivers depend on these components. How are we going to manage these common modules in case each driver is updated separately? What if one makes a change in such common module, which makes it incompatible with any of dependent drivers?

**Comment by jlipps** [comment]
@mykola-mokhnach here's the planned dependency graph for the current set of drivers. (Of course under my new proposal, the drivers will not be strict code dependencies of Appium until they are "installed").

![appium-planned](https://cloud.githubusercontent.com/assets/605053/24833339/c55f900c-1c7a-11e7-8fee-6ca6a5219ff0.png)

Basically, some common modules will continue to exist independently and be shared. Or in many cases as we already do, some common functionality will reside in the older driver and the newer driver will depend on it. Just as appium-uiautomator2-driver depends on appium-android-driver currently. Once appium-android-driver goes away permanently, code can be ported to appium-uiautomator2-driver.

If necessary, we can also pull code into its own package/repo, though we've been trying to minimize the number of repos needed. Basically we'd only want a separate repo when a separate group is maintaining it, or when multiple separate maintainer groups need to reference a common set of code.

**Comment by mykola-mokhnach** [comment]
Yup, this new architecture looks more clear, than the current one, but my intuition says it will require the most of effort to decouple these modules in their current state.

Also, I'd like to mention the second thing, which seems important to me, and which we discussed before. We could get rid of babel transpilation step and use native ES6 support provided by recent NodeJS versions.

**Comment by dpgraham** [comment]
I've thought about this a fair bit as well.

I think we should consider having local Appium as well as the global CLI (similar to eslint, babel, karma, webpack, etc...)

The idea I had was that Appium could be used as a NodeJS dependency and the Appium drivers would be dependencies that follow the naming convention of `appium-<driverName>-driver`. Then when running an Appium test, you simply specify the driverName, let's say, xcuitest, and it will look for `appium-xcuitest-driver` in the dependencies and use that. (This is similar to how babel presets, karma launchers, webpack loaders and eslint plugins work)

The benefits of this are
* Teams can ensure that everyone is using the same version of Appium and the same versions of the Appium drivers
* Teams can upgrade everyone to the latest versions of Appium or Appium Drivers by simply updating the package.json
* The configuration required to run Appium in a CI environment would be reduced

**Comment by dpgraham** [comment]
@mykola-mokhnach I agree that we should look into Node 8 and see if it has the language level support we need. I don't think we can drop the transpilation step though until we drop support for any version of Node < 8, but in the interim we can do a version checks if it's >= 8 and if it is use the untranspiled source code, otherwise use the transpiled code.

**Comment by jlipps** [comment]
@mykola-mokhnach @dpgraham I think the only significant feature we need to transpile that Node 7.x don't support is `import`, right? Is Node 8 planning on supporting that? Given that Appium 2.0 is still probably some ways away, I'd be fine making a hard break and requiring support of Node 8 if that's what it takes not to have to transpile anymore.

**Comment by mykola-mokhnach** [comment]
http://node.green/

**Comment by dpgraham** [comment]
@mykola-mokhnach Which one of these features is `import`. I searched for the keyword import and couldn't find anything. Does it have a different name?

**Comment by mykola-mokhnach** [comment]
@dpgraham There is no import there. And the second article says developers are working on the implementation, but no strict deadline is set. So it is unclear whether the feature is going to be supported in NodeJS 8

**Comment by jlipps** [comment]
Yeah, in that case our options are to either rewrite our code so that we use require instead of import, or to keep transpilation of imports only.

**Comment by rkavalap** [comment]
I like the idea main appium repo acting as an orchestrator. 
If that happens I would ideally want each individual driver to be controllable programatically as in passing args or config as command line params. Then if the end user wants only a particular driver can install and launch just that driver even without the main appium package

**Comment by mykola-mokhnach** [comment]
I vote for transpilation on minimum level. This will require less effort. We can also transition to babel6 and fix several deprecation warnings we have on Appium install

**Comment by tirodkar** [comment]
Hey @jlipps, quick question - were you planning to add support for any other platform specific testing frameworks as well? I work with [EarlGrey](https://github.com/google/EarlGrey) and it would be great if Appium was integrated with it as well. Not sure what the integration requirements would be from the Appium side as of now.

**Comment by jlipps** [comment]
@tirodkar hello! we'd absolutely love to integrate EarlGrey via an EarlGrey driver for Appium. Architecturally, there would be two pieces:

1. a webdriver protocol-compatible HTTP server built into EarlGrey itself (written in ObjC or whatever EarlGrey is written in). This listens for requests and performs automation actions based on the request.
2. an Appium driver proxy, written in JS and hosted on NPM. This is the glue between Appium and EarlGrey, that enables Appium users access to EarlGrey. It will bundle the EarlGrey code or binary and handle whatever launch invocations EarlGrey requires in addition to proxying to the webdriver server running in EarlGrey.

The EarlGrey team would need to handle (1), since the Appium team doesn't know anything about that. The Appium team can handle (2), or walk you through creating that (there are a number of examples of this and it's a pretty minimal set of code that's required).

Of course, we can also consult on the design of (1), and that might be a good idea to avoid any incompatibilities.

The end result would be all Appium users having access to the EarlGrey technology via the universal WebDriver protocol--a real win for everyone! Please stay in touch as we'd love to facilitate this happening.

**Comment by yaphatak** [comment]
@jlipps & @tirodkar  It will be good to have EarlGrey within appium. It is more stable and flexible than WDA in lots of aspects.

**Comment by yaphatak** [comment]
@jlipps doesnt it make sense to have 'xcuitest-driver', in future earlgrey driver to derive from 'iosdriver'. iOSDriver can do common thing of starting clear session (uninstall old app, install new app, other ios-only capability driven tasks)
Same holds true for 'android-driver'

**Comment by tirodkar** [comment]
> a webdriver protocol-compatible HTTP server built into EarlGrey itself (written in ObjC or whatever EarlGrey is written in). This listens for requests and performs automation actions based on the request.

Thanks for the info @jlipps. We're currently working on our next version of EarlGrey which will be based on XCUITest as well and we'd love to incorporate the HTTP server for webdriver. We'll keep you updated.

++ @wuhao5 @khandpur, also from the EarlGrey team.

**Comment by moizjv** [comment]
This is so exciting.!

**Comment by jlipps** [comment]
@appium/committers I updated the main issue here to start a list of all the breaking changes we want to make with appium 2.0. Let's make sure to think of everything we might want to do!

**Comment by tirodkar** [comment]
Would appium 2.0 be integrated with XCUITest?

**Comment by mykola-mokhnach** [comment]
Closed as completed
