### ISSUE TITLE
Roadmap for getting driver into working order

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7422]
@imurchie commented on [Fri Jul 08 2016](https://github.com/appium/appium-xcuitest-driver/issues/53)

## Work to be done

[Appium iOS endpoints](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/endpoints.md)

[WDA endpoints](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/endpoints-wda.md)

The `appium-safari-driver` needs much work. 
### Session commands:
- [ ] Handle the optional `requiredCapabilities` that Appium supports
### Selenium commands
- [x] Navigation commands (`forward`, `back`, `refresh`)
- [ ] element submit
- [ ] element selected
- [ ] element equals other element
- [ ] touch commands
  - [ ] moveto
  - [ ] click
  - [ ] flick
- [ ] get geo location 
- [ ] set geo location
- [x] get log types
- [x] get logs 
- [ ] Tests
  - [x] screenshot
  - [x] window size
  - [x] find commands (single, multiple, in the context of another element)
  - [x] element text
  - [x] element set value
  - [x] keys
  - [x] element name
  - [x] element clear
  - [x] element displayed
  - [x] element location
  - [x] element location_in_view
  - [x] element size
  - [x] get orientation
  - [x] set orientation
### Appium commands

All Appium-specific commands need to be implemented. This is mostly involving 
looking at `appium-ios-driver` and seeing how to reorganize it to allow us to 
import those methods here. Anything that requires UIAutomation and Instruments 
will have to have that factored out so that we can make the appropriate calls
to WDA, if available.

Some things in particular:
- [ ] touch actions 
- [ ] touch multi actions

---

@imurchie commented on [Fri Jul 08 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-231416414)

I am working on tests for the find commands at the moment.

---

@imurchie commented on [Tue Jul 12 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-232126457)

Taking on screenshotting.

---

@imurchie commented on [Mon Jul 18 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-233362468)

Beginning the element tests.

---

@yaphatak commented on [Mon Aug 01 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-236672027)

@imurchie : Just want to add this for general discussion.
Don't you think  all safari end points should go through xcuitest-driver rather than calling them directly like this https://github.com/appium/appium-xcuitest-driver/blob/master/lib/driver.js#L309-L312.
This (https://github.com/appium/appium-ios-driver/blob/master/lib/commands/find.js#L15-L19) should be preferred approach. So that say if there is alert that we want to dismiss while doing web action we can do that. With todays design its almost impossible to do that.

---

@imurchie commented on [Mon Aug 01 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-236714588)

I completely agree. The way it is done now is entirely provisional and, I think, not scalable.

---

@rz-robsn commented on [Mon Aug 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-239823662)

Just letting you guys know in case you did not already, but Apple removed the deprecated Automation instrument from Instruments in their latest XCode Beta (version 5). 

---

@imurchie commented on [Mon Aug 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-239824033)

Yes. They removed from the first Beta.

That's why we are working hard on getting XCUITest integration so iOS 10 can be automated!

---

@imurchie commented on [Fri Aug 26 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-242849622)

I think the biggest thing at the moment is dealing with touch actions. What is supported? What can WDA do? How can we at least approximate some of the functionality?

---

@imurchie commented on [Fri Aug 26 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-242851178)

Also left to do is document and test the `-ios predicate string` locator strategy.

---

@yaphatak commented on [Sun Aug 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/53#issuecomment-242998903)

https://github.com/appium/appium-xcuitest-driver/pull/113

This is for gestures like longpress, swipe, drag.

Issue with WDA is, it doesnt support longpress, doubletap without element. So you have to have element. Also long press needs duration for which it need to be long pressed. You can look at PR for details.
